# Generated by Django 4.2.3 on 2023-07-29 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Venue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('address', models.CharField(max_length=300)),
                ('pin_code', models.CharField(max_length=6)),
                ('phone', models.CharField(max_length=15)),
                ('web_address', models.URLField()),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
    ]
